chucknorris/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import i18n_patterns

from . import views


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('result/<str:pk>', views.ResultView.as_view(), name='result_detail'),
    path('change-language', views.change_language, name='change_language'),
    path('', views.search, name="search_page")
)

chucknorris/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.translation import ugettext_lazy as _

import requests, json, urllib

class ApiChuckNorris:
    ENDPOINT = "https://api.chucknorris.io/jokes"
    ENDPOINT_RANDOM = ENDPOINT + "/random"
    ENDPOINT_CATEGORIES = ENDPOINT + "/categories"
    ENDPOINT_SEARCH = ENDPOINT + "/search"

    def get_categories():

        response = requests.get(ApiChuckNorris.ENDPOINT_CATEGORIES)
        if response.status_code != 200:
            raise Exception('ApiChuck is not responding')
        
        categories = []
        for category in json.loads(response.text):
            categories.append((category, category.capitalize()))

        return categories

    def search(text):

        args = {'query': text}
        response = requests.get(ApiChuckNorris.ENDPOINT_SEARCH+'?'+urllib.parse.urlencode(args))
        if response.status_code != 200:
            raise Exception('ApiChuck is not responding')

        return json.loads(response.text).get('result')

    def random(category = None):
        args = {}
        if category is not None:
            args['category'] = category

        if len(args) > 0:
            response = requests.get(ApiChuckNorris.ENDPOINT_RANDOM+'?'+urllib.parse.urlencode(args))
        else:
            response = requests.get(ApiChuckNorris.ENDPOINT_RANDOM)

        if response.status_code != 200:
            raise Exception('ApiChuck is not responding')
        
        return json.loads(response.text).get('value')
        
def get_category_choices():
    return [('', '--')]+ApiChuckNorris.get_categories()

class Search(models.Model):
    TYPE_WORDS = 'words'
    TYPE_CATEGORY = 'category'
    TYPE_RANDOM = 'random'

    SEARCH_TYPE_CHOICES = (
        (TYPE_WORDS, _('Words')),
        (TYPE_CATEGORY, _('Category')),
        (TYPE_RANDOM, _('Random'))
    )

    search_type = models.CharField(_('Search Type'), choices=SEARCH_TYPE_CHOICES, max_length=8, default=TYPE_WORDS)
    category = models.CharField(_('Category'), max_length=100, null=True, blank=True, choices=get_category_choices())
    search = models.CharField(_('Search Query'), max_length=200, null=True, blank=True)
    email = models.EmailField(_('Email'), blank=True, null=True)

    @staticmethod
    def get_types():
        return (Search.TYPE_WORDS, Search.TYPE_RANDOM, Search.TYPE_CATEGORY)

class Result(models.Model):
    search = models.OneToOneField(Search, on_delete=models.CASCADE)
    data = models.JSONField()

    def is_multiresult(self):
        return self.search.search_type == Search.TYPE_WORDS

    def get_absolute_url(self):
        return reverse("result_detail", kwargs={"pk": self.pk})
    

chucknorris/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from .models import Search, ApiChuckNorris

class SearchForm(forms.ModelForm):
    search_type = forms.TypedChoiceField(label=_('Search Type'), initial=Search.TYPE_WORDS ,choices=Search.SEARCH_TYPE_CHOICES, widget=forms.RadioSelect)

    def clean(self):
        super().clean()
        search_type = self.cleaned_data.get('search_type')
        search = self.cleaned_data.get('search')
        category = self.cleaned_data.get('category')

        # Validate category requirement
        if search_type == Search.TYPE_CATEGORY and category is None:
            self.add_error('category', ValidationError('You must select one category'))
        elif search_type == Search.TYPE_WORDS and search is None:
            self.add_error('search', ValidationError('You must enter a text to search by words'))
    
        return self.cleaned_data
            

    class Meta:
        fields = ('search_type', 'category', 'search', 'email')
        model = Search

chucknorris/views.py
from django.shortcuts import render, redirect
from .forms import SearchForm
from .models import Search, ApiChuckNorris, Result
from django.http import HttpResponseForbidden
from django.views.generic.detail import DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.translation import gettext as _
from django.http import HttpResponseRedirect
from django.conf import settings

def search(request):
    """
    Search view responsible to show search form and store search and result data. Also if user insert an email, an email with
    results will be sent to the user
    """
    if request.method == 'POST':

        search_type = request.POST.get('search_type')
        search = request.POST.get('search')
        category = request.POST.get('category')

        if search_type not in Search.get_types():
            # Raise 403 not allowed if type is not one of our types
            return HttpResponseForbidden('Search type not allowed')

        form = SearchForm(request.POST)
        if form.is_valid():

            # Get result from api
            if search_type == Search.TYPE_WORDS:
                result = ApiChuckNorris.search(search)
            elif search_type == Search.TYPE_CATEGORY:
                result = ApiChuckNorris.random(category)
            elif search_type == Search.TYPE_RANDOM:
                result = ApiChuckNorris.random()

            # Save Search
            search = form.save()

            # Save search and result
            result = Result.objects.create(search=search, data=result)

            # If search has email sent results to mail
            send_mail(
                _('Your ApiChuck Search Results'),
                render_to_string('mail/result.html', {'result': result}), 
                'apichuck@apichuck.com',
                [search.email]
            )

            # Redirect to result page
            return redirect(result.get_absolute_url())

        return render(request, 'search.html', {"form": form })
    # If it's not post return form
    form = SearchForm()

    return render(request, 'search.html', {"form": form })

class ResultView(DetailView):
    template_name = 'result.html'
    model = Result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page')

        result = self.get_object()
        paginator = Paginator(result.data, 10)
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)

        context["data"] = data

        return context

def change_language(request):
    response = HttpResponseRedirect('/')
    if request.method == 'POST':
        language = request.POST.get('language')
        if language:
            if language != settings.LANGUAGE_CODE and [lang for lang in settings.LANGUAGES if lang[0] == language]:
                redirect_path = f'/{language}/'
            elif language == settings.LANGUAGE_CODE:
                redirect_path = '/'
            else:
                return response
            from django.utils import translation
            translation.activate(language)
            response = HttpResponseRedirect(redirect_path)
            response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
            
    return response
    

chucknorris/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}Default Title{% endblock  %}</title>
        
        {% comment %} STYLES {% endcomment %}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    </head>
    <body>

        <div class="container is-max-widescreen">
            <div class="columns ">
                <div class="column has-text-centered">
                    <a class="hvr-buzz-out" href="/" title="Chuck Norris Jokes">
                        <figure class="image is-inline-block">
                            <img style="max-width:300px;" alt="Chuck Norris Jokes" src="https://api.chucknorris.io//img/chucknorris_logo_coloured_small.png" srcset="https://api.chucknorris.io//img/chucknorris_logo_coloured_small@2x.png 720w">
                        </figure>           
                    </a>
                </div>
            </div>
            {% block content %}{% endblock %}
        </div>
        
        {% block js %}{% endblock %}

        <footer class="footer">
            
            <script defer>
                class LanguageManager {
                    constructor() {
                        this.form = document.querySelector('#language-form');
                        this.select = document.querySelector('#language-select');

                        this.select.addEventListener('change', () => {
                            this.form.submit();
                        });
                    }
                }

                document.addEventListener('DOMContentLoaded', () => {
                    window.LanguageManager = new LanguageManager();
                });
            </script>

            <div class="columns column is-2">
                <form action="{% url 'change_language' %}" method="post" id="language-form">
                    {% csrf_token %}
                    <div class="select">
                        <select name="language" id="language-select">   
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% for language in LANGUAGES %}       
                            <option value="{{ language.0 }}" {% if language.0 == LANGUAGE_CODE %} selected{% endif %}>
                                {{ language.0|language_name_local }} ({{ language.0 }})
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                </form>
            </div> 
            <div class="content has-text-centered">
                <p>
                    <strong>{% trans "© 2020 Chucknorris Jokes by Joel Jiménez - Metadata by api.chucknorris.io" %}</strong>
                </p>
            </div>
        </footer>
    </body>
</html>

chucknorris/templates/forms/field.html
{% load form_tags %}

<div class="field">
{{field.field.widget.}}
    {% if field.field.widget.input_type == 'checkbox' %}
        {{ field.label_tag | add_tag_class:"checkbox" | safe }}
        {{ field }}
    {% elif field.field.widget.input_type == 'radio' %}
        {{ field.label_tag | add_tag_class:"radio" | safe }}
        {{ field }}
    {% elif field.field.widget.input_type == 'select' %}
        {{ field.label_tag }}
        {{ field }}
    {% elif field.field.widget|to_class_name == "Textarea" %}
        {{ field.label_tag | add_tag_class | safe }}
        <div class="control">
            {% if field.errors|length  > 0 %}
                {% with extra_class="textarea is-danger" %}     
                    {{ field | bulma_input:extra_class }}
                {% endwith %}
            {% else %}
                {% with extra_class="textarea" %}     
                    {{ field | bulma_input:extra_class }}
                {% endwith %}
            {% endif %}
        </div>
    {% else %}
        {{ field.label_tag | add_tag_class | safe }}
        <div class="control">
            {% if field.errors|length  > 0 %}
                {% with extra_class="input is-danger" %}     
                    {{ field | bulma_input:extra_class }}
                {% endwith %}
            {% else %}
                {% with extra_class="input" %}     
                    {{ field | bulma_input:extra_class }}
                {% endwith %}
            {% endif %}
        </div>
    {% endif %}
    {% for error in field.errors %}
        <p class="help is-danger">{{ error }}</p>
    {% endfor %}
</div>

chucknorris/templates/result.html
{% extends 'base.html' %}

{% load i18n utils_tags %}

{% block content %}

{% if result.is_multiresult %}
    <h1 class="title">{% blocktrans with search=result.search.search %}Result for: {{ search }}{% endblocktrans %}</h1>
    <div class="content">
        {% for item in data %}
            <div class="box">
                {{ item.value }}
            </div>
        {% endfor %}
    </div>

    {% if data.has_other_pages %}
    <nav class="pagination is-rounded" role="navigation" aria-label="pagination">
        {% if data.has_previous %}
            <a class="pagination-previous" href="?page={{ data.previous_page_number }}">{% trans "Previous" %}</a>
        {% endif %}

        {% if data.has_next %}
            <a class="pagination-next" href="?page={{ data.next_page_number }}">{% trans "Next" %}</a>
        {% endif %}

        <ul class="pagination-list">
            {% for i in data.paginator.page_range %}
            {% if data.number == i %}
                <li class="active"> <a class="pagination-link is-current">{{ i }}</a></li>
            {% else %}
                <li><a class="pagination-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>
    {% endif %}
{% else %}
    <h1 class="title">{% trans "Result" %}</h1>
    <div class="box">
        {{ result.data }}
    </div>
{% endif %}


{% endblock content %}

chucknorris/templates/search.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}

<form method="post">
    {% csrf_token %}

    {% for field in form %}
        {% include 'forms/field.html' %}
    {% endfor %}

    {% if form.non_field_errors %}
        <span class="help is-danger">{{ form.non_field_errors }}</span>
    {% endif %}

    <button class="button is-success" type="submit">{% trans 'Get a Joke!' %}</button>
</form>

{% endblock content %}

{% block js %}

<script>

class SearchFormManager {
    constructor() {
        this.searchTypeInput = document.querySelectorAll('input[name="search_type"]');
        this.searchInput = document.querySelector('#id_search');
        this.categoryInput = document.querySelector('#id_category');
        
        this.searchTypeInput.forEach(input => {
            input.addEventListener('change', event => {
                this.refreshDisplay();
            });
        });
    }

    refreshDisplay() {
        let checked = null;
        this.searchTypeInput.forEach(input => {
            if(input.checked) {
                checked = input
            }
        });

        if(checked.value == 'words') {
            this.searchInput.closest('.field').classList.remove('is-hidden');
            this.categoryInput.closest('.field').classList.add('is-hidden');
        } else if(checked.value == 'category') {
            this.searchInput.closest('.field').classList.add('is-hidden');
            this.categoryInput.closest('.field').classList.remove('is-hidden');
        } else if(checked.value == 'random'){
            this.searchInput.closest('.field').classList.add('is-hidden');
            this.categoryInput.closest('.field').classList.add('is-hidden');
        } else {
            console.error('Please select search type.')
        }
    }
}

document.addEventListener('DOMContentLoaded', () => {
    window.SearchFormManager = new SearchFormManager();
    window.SearchFormManager.refreshDisplay();
});

</script>

{% endblock js %}